name: Update blog posts

on:
  schedule:
    - cron: "0 0 * * *" # 매일 09:00 (KST)
  workflow_dispatch: # 수동 실행 버튼

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://sunghoyaaa.com/rss.xml"
          max_post_count: 5
